language: android
android:
  components:
  - tools
  - tools
  - platform-tools
  - build-tools-24.0.2
  - android-25
  - extra-android-m2repository
jdk:
- oraclejdk8
script:
- ./gradlew ":library:build"
after_success:
- ".buildscript/deploy_snapshot.sh"
branches:
  except:
  - gh-pages
notifications:
  email: false
sudo: false
cache:
  directories:
  - "$HOME/.gradle"