language: android
android:
  components:
  - tools
  - tools
  - platform-tools
  - build-tools-24.0.2
  - android-25
  - extra-android-m2repository
jdk:
- oraclejdk8
script:
- ./gradlew ":library:build"
after_success:
- ".buildscript/deploy_snapshot.sh"
env:
  global:
  - secure: jzfc/pBFM1yAZabj9vwvApjb6Zj8Xpffs3F4yux6AsaNiOFdscAejQ2fEYOpg3U7VfaKhcjMMr0mXKo3jY7tmmTuv73LKOGp+0PQ9Xf9Tl+6KKeESlrdOt6fQOlCZVLW7TziabTLxf5dABoyccHgomk3JPgAImpgcJKdcQIh3pPRZCRfTceCwBYZYRgSD9ohiOusiTOhDSC/nKFZFkGPkLkxDtvhul3i5qgp9MAbdUiuURrpVbgNZZuyHB0JZheQspWR7I4UmOJ52CLqv5ugHNRh/ROL5x22O/3tDjXgKJnR/q2Qty9qzowi47vsFS421ALJsoBTBi13CVQrgZVDZ8agVY5hI5ontvsoulJLajaU2wm6SS/E9X3aTiTqv9ND6UnwOKa5js5UwMXdqzvSiQbFH5F7P4yRJdRvd3//Q4W+0tBJwNXTdv5D6vZViBM5k3lDXHcQSIM6g9HEiKKtOGyNBupDA/TLkowaa85TuF/wCcVx0JybD/rcbYkZolYVJHFU99mPez45aG1ImRhuecRazSSW/jECfaGNGpMV6tzH2DnPFhgzqS25tZmxpj6kWucJnW89sIU52XI2Nn1trZSoftSo/tCzAuHo7RGH5SHIt1SR7fGTRw+d7pPbUxp4vKh7aAXdb6S0ynsXee6arjSWDdvQ9zUxjlBWFQcJTGk=
  - secure: kN+JxXukk/Zkz14fIYIBS9x7UHQCZloIWeHWYjmfPExqFnSwDMgN2LTKRK/3kuIzYaav3Psknyh4lBKrpu9iC9v4w60IPSFYyLCVZcuBO+9hxbBK2ECZf1nk0MmhhScQRAwLlSncUKCOL0WPBGiJGbrc9wWSiAqz/2THtwHXbZ9YGmKRLXrt9L/4iow8Z61jb6Mio8R6tgNNWxb3q8ID7UnO6DD7OCR2i/OFiNeD7uswk2H28dEixOdv5TOMn5gImWlIf5du/L8s4ODrRdrZ1lhnHn84ZA/rUKu9jPrC1DYGOJmNw5HMHoNz/Vm67nklX1tG1kzbeFckjxhSPTh9MaUmdOkJM8ejy3TkNddZ7GbMak0bxCPx1hHC7xqBM0kSmqvcwi0AopcyJVt1i8AJ7a0ZFoFIhZrG3+Fhpy6tU1tJjOMMpFbMd61FrVZuvcLdELex3BzDxn4rnw2ZoTrSFJ7KY/+tLts0AKdfLhgHmt/qNK1dvp/qICQrpgZSTLvnAejf/N1tfc4GBr3km03uXXG2pabD29kZfNgVz/BkuFenWxgoVqO3xWTdfMHw46AC2nPwagvSUGacoRaMPBrjjHGF97aOe/KzkIXHTixVWhKgigkbnd7xHECMc+JXG9NfgUKZPhe7vd6YGUi65AqYWY5SMiS61XIdnFcWuFrLWp0=
branches:
  except:
  - gh-pages
notifications:
  email: false
sudo: false
cache:
  directories:
  - "$HOME/.gradle"
